name: pggan
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - numpy=1.13.3
  - scipy=1.0.0
  - tensorflow-gpu=1.6.0
  - cryptography=2.1.4
  - h5py=2.7.1
  - six=1.11.0
  